limitrange-container: {}               # ranges and quotas set by default for each CONTAINER that has not configured their own requests and limits
#  request:                            # default requests for one container
#    cpu: "10m"
#    memory: "32Mi"
#    ephemeral-storage: "100Mi"
#  limit:                              # default limits for one container
#    cpu: "300m"
#    memory: "512Mi"
#    ephemeral-storage: "1Gi"
#  min:                                # a container can't request less than the values
#    cpu: "10m"
#    memory: "32Mi"
#    ephemeral-storage: "100Mi"
#  max:                                # a container can't request more than the values
#    cpu: "1600m"
#    memory: "7Gi"
#    ephemeral-storage: "10Gi"

limitrange-pod: {}                     # PODs can't request resources beyond the limits
#  min:                                # a pod can't request less than the values
#    cpu: "10m"
#    memory: "32Mi"
#    ephemeral-storage: "100Mi"
#  max:                                # a pod can't request more than the values
#    cpu: "500m"
#    memory: "5Gi"
#    ephemeral-storage: "5Gi"

limitrange-pvc: {}                     # one PersistentVolumeClaim can't request resources beyond the limits
#  min:                                # a PVC can't request less than the values
#    storage: "0"
#  max:                                # a PVC can't request more than the values
#    storage: "0"

general: {}                            # default quotas for the entire namespace for all pods without priority classes
#  pods: "200"
#  requests.cpu: "4"
#  requests.memory: "32Gi"
#  requests.ephemeral-storage: "64Gi"
#  requests.storage: "0"
#  limits.cpu: "8"
#  limits.memory: "64Gi"
#  limits.ephemeral-storage: "128Gi"
#  count/persistentvolumeclaims: "0"
#  count/services: "30"
#  services.loadbalancers: "15"
#  services.nodeports: "0"
#  count/secrets: "1000"
#  count/configmaps: "1000"
#  count/replicationcontrollers: "0"
#  count/deployments.apps: "30"
#  count/replicasets.apps: "90"
#  count/statefulsets.apps: "0"
#  count/jobs.batch: "30"
#  count/cronjobs.batch: "10"
#  count/ingresses.extensions: "10"

high: {}                                # total quotas for the entire namespace for all pods with PriorityClass: "high"
#  pods: "200"
#  requests.cpu: "4"
#  requests.memory: "32Gi"
#  requests.ephemeral-storage: "64Gi"
#  requests.storage: "0"
#  limits.cpu: "8"
#  limits.memory: "64Gi"
#  limits.ephemeral-storage: "128Gi"
#  count/persistentvolumeclaims: "0"
#  count/services: "30"
#  services.loadbalancers: "15"
#  services.nodeports: "0"
#  count/secrets: "1000"
#  count/configmaps: "1000"
#  count/replicationcontrollers: "0"
#  count/deployments.apps: "30"
#  count/replicasets.apps: "90"
#  count/statefulsets.apps: "0"
#  count/jobs.batch: "30"
#  count/cronjobs.batch: "10"
#  count/ingresses.extensions: "10"

medium: {}                              # total quotas for the entire namespace for all pods with PriorityClass: "medium"
#  pods: "200"
#  requests.cpu: "4"
#  requests.memory: "32Gi"
#  requests.ephemeral-storage: "64Gi"
#  requests.storage: "0"
#  limits.cpu: "8"
#  limits.memory: "64Gi"
#  limits.ephemeral-storage: "128Gi"
#  count/persistentvolumeclaims: "0"
#  count/services: "30"
#  services.loadbalancers: "15"
#  services.nodeports: "0"
#  count/secrets: "1000"
#  count/configmaps: "1000"
#  count/replicationcontrollers: "0"
#  count/deployments.apps: "30"
#  count/replicasets.apps: "90"
#  count/statefulsets.apps: "0"
#  count/jobs.batch: "30"
#  count/cronjobs.batch: "10"
#  count/ingresses.extensions: "10"

low: {}                                  # total quotas for the entire namespace for all pods with PriorityClass: "low"
#  pods: "200"
#  requests.cpu: "4"
#  requests.memory: "32Gi"
#  requests.ephemeral-storage: "64Gi"
#  requests.storage: "0"
#  limits.cpu: "8"
#  limits.memory: "64Gi"
#  limits.ephemeral-storage: "128Gi"
#  count/persistentvolumeclaims: "0"
#  count/services: "30"
#  services.loadbalancers: "15"
#  services.nodeports: "0"
#  count/secrets: "1000"
#  count/configmaps: "1000"
#  count/replicationcontrollers: "0"
#  count/deployments.apps: "30"
#  count/replicasets.apps: "90"
#  count/statefulsets.apps: "0"
#  count/jobs.batch: "30"
#  count/cronjobs.batch: "10"
#  count/ingresses.extensions: "10"
