{{- if $limitrange := index .Values "limitrange-container" -}}
{{- $request := index $limitrange "request" -}}
{{- $limit := index $limitrange "limit" }}
{{- $min := index $limitrange "min" -}}
{{- $max := index $limitrange "max" }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: "{{ .Release.Namespace }}-container"
spec:
  limits:
    - type: Container
      {{- if $request }}
      defaultRequest:
      {{- range $k, $v := $request }}
        {{ $k }}: {{ $v | quote }}
      {{- end }}
      {{- end }}
      {{- if $limit }}
      default:
      {{- range $k, $v := $limit }}
        {{ $k }}: {{ $v | quote }}
      {{- end }}
      {{- end }}
      {{- if $min }}
      min:
      {{- range $k, $v := $min }}
        {{ $k }}: {{ $v | quote }}
      {{- end }}
      {{- end }}
      {{- if $max }}
      max:
      {{- range $k, $v := $max }}
        {{ $k }}: {{ $v | quote }}
      {{- end }}
      {{- end }}
{{- end }}
